joinAndQuitMessage:
  join: "<gray>[<green>+<gray>] <white>%player_name% <gray>加入了游戏。"
  quit: "<gray>[<red>+<gray>] <white>%player_name% <gray>退出了游戏。"

tablist:
  header:
    - "如果说这个时候有一个苦力怕把你马炸死了"
  footer:
    - "那么会非常心疼的"

armorMenu:
  title: "<player>"

chatFormat:
  format: "<white><player>: <gray><message>"
  linkHighlight:
    hover: "<aqua>点击打开！"

locale:
  succeed: "<green>成功。"
  tpsWarn: "<red>服务器每秒执行的刻已经小于 18。<br><red>你会感受到明显的卡顿。<br><red>请不要长时间呆在实体多的区块和开着卡服务器的机器。<br><red>谢谢合作。"