joinAndQuitMessage:
  join: "<gray>[<green>+<gray>] <white>%player_name% <gray>加入了游戏。"
  quit: "<gray>[<red>+<gray>] <white>%player_name% <gray>退出了游戏。"
tablist:
  header:
    - "如果说这个时候有一个苦力怕把你马炸死了"
  footer:
    - "那么会非常心疼的"

locale:
  gameModeWarn: "<red>检测到你的游戏模式被未许可的方式更改了。<br><red>这次更改的操作已经被阻止。<br><red>如果这是管理员帮你修改的，请联系他。"