name: plutocore
version: 1.0.0
main: top.plutomc.plutocore.CorePlugin
author: GerryYuu
api-version: 1.13
depend:
  - PlaceholderAPI
description: FUCK YOU PAPERMC
permissions:
  plutocore:
    children:
      cmd:
        description: cmd
      gamemode:
        description: gamemode
commands:
  plutocore:
    permission: plutocore.cmd
  gm:
    permission: plutocore.gamemode
    aliases:
      - mode
