name: plutocore
version: 1.0.0
main: top.plutomc.plutocore.CorePlugin
author: GerryYuu
api-version: 1.13
depend:
  - PlaceholderAPI
  - NBTAPI
description: FUCK YOU PAPERMC
permissions:
  plutocore:
    children:
      cmd:
        description: cmd
      gamemode:
        description: gamemode
commands:
  plutocore:
    permission: plutocore.cmd
    description: plutocore
  tickpersecond:
    description: tps
    aliases:
      - tick
  gm:
    permission: plutocore.gamemode
    description: gm
    aliases:
      - mode
